# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7d2cdcc62f9750d4612c04cce3a66c55086f6ca129558659fe4c8c024c306f383010c4b344d0b662b20e0840dbe56b80e00981190a1d5e2838b67885e81df31b

test:
  secret_key_base: 49bc257e7ec5f15c1e837da41f3102bbcd2fa08df452225df3ef668765c6232eb4408a42c92a773fd0d1b28566c8903808946ecb9cd5f3d722003bdb8b5191d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
